<?php
/**
 * @author Danilo Eidy Ramazzotti Suguimoto
 */

/**
 * @var Page $block
 */

use Webjump\HelloWorld\Block\HelloWorld\Page;
?>
<hr>
<div class="additional-content">
    <div class="block block-dashboard-info">
        <div class="block-content">
            <div class="box box-information">
                <strong class="box-title">
                    <span><?= __('Additional Content'); ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?= __('This block was added by the template in theme-frontend-helloworld!') ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
